### ISSUE TITLE
Add command access

### ISSUE THREAD

**Issue by Laraakaa** [Twasi/twasi-commands#3]
Every command should have it's own access level:

Every group should inherit the upper one.

- Every user
- Subscriber
- Moderator
- Streamer

**Comment by DieserMerlin** [comment]
Access levels are integrated now. To change it use the !setaccess command. The following levels are available (descending):

- Broadcaster
- Moderator
- VIP
- Subscriber
- Follower
- Viewer (everyone)

Mods can use the !setaccess command too except the command they try to change has "broadcaster" as access level.

https://github.com/Twasi/twasi-commands/compare/b7afbc3b9f67895c2ca8a5b1c19bf142c713ea2c...3dd73c8b9a7579fc791949df1594f039daece72a
